FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY scripts ./scripts
COPY assets ./assets

RUN ./scripts/install-tex.sh

ENV TECTONIC_CACHE_DIR=/opt/tectonic-cache

EXPOSE 5000

CMD ["node", "--watch", "src/server.js"]
